// Browser Supabase client for Zari Boutique's own Supabase project.
//
// This intentionally does NOT use src/integrations/supabase/client.ts: that file and
// the .env values next to it are regenerated by the platform and pinned to a different
// project. This client is the single source of truth for the app.
//
// Production (Vercel): set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY.
// Only the publishable (anon) key belongs here — never a service-role/secret key.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./database.types";

/** The Supabase project this app is built against. */
export const ZARI_PROJECT_REF = "ubmxuhzlvyjomuopcoxk";

// Used when the build environment has no VITE_* values, or when it still carries a
// different project's values (as the local Lovable preview does). Both are public.
const DEFAULT_URL = `https://${ZARI_PROJECT_REF}.supabase.co`;
const DEFAULT_PUBLISHABLE_KEY = "sb_publishable_4HVRiWgOTNeHeYzF6JBPSQ_Dz-3q1eN";

const envUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

const usingEnv = Boolean(envUrl && envKey && envUrl.includes(ZARI_PROJECT_REF));

export const SUPABASE_URL = usingEnv ? envUrl! : DEFAULT_URL;
export const SUPABASE_PUBLISHABLE_KEY = usingEnv ? envKey! : DEFAULT_PUBLISHABLE_KEY;

/** Where the client got its config from — handy when diagnosing a deployment. */
export const supabaseConfigSource: "env" | "fallback" = usingEnv ? "env" : "fallback";

// New-format sb_publishable_ keys are opaque strings, not JWTs: PostgREST rejects them
// when they arrive as an Authorization bearer, so send them only as `apikey`.
function zariFetch(key: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );
    if (init?.headers) new Headers(init.headers).forEach((v, k) => headers.set(k, v));
    if (key.startsWith("sb_") && headers.get("Authorization") === `Bearer ${key}`) {
      headers.delete("Authorization");
    }
    headers.set("apikey", key);
    return fetch(input, { ...init, headers });
  };
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: { fetch: zariFetch(SUPABASE_PUBLISHABLE_KEY) },
  auth: {
    storage: typeof window !== "undefined" ? window.localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: typeof window !== "undefined",
  },
});

/** Storage bucket holding product imagery (public bucket). */
export const PRODUCT_IMAGE_BUCKET = "product-images";

/** Turns any Supabase/network failure into a message a shopper can act on. */
export function describeError(err: unknown, fallback = "Something went wrong."): string {
  if (!err) return fallback;
  if (typeof err === "string") return err;
  const anyErr = err as { message?: string; error_description?: string; hint?: string };
  const raw = anyErr.message ?? anyErr.error_description ?? "";
  if (!raw) return fallback;
  const lower = raw.toLowerCase();
  if (lower.includes("failed to fetch") || lower.includes("fetch failed") || lower.includes("networkerror")) {
    return `Could not reach the Zari server (${new URL(SUPABASE_URL).host}). Check your connection and try again.`;
  }
  if (lower.includes("row-level security")) {
    return "You don't have permission to do that.";
  }
  return raw;
}
